(define (problem p1)
  (:domain exploding-blocksworld)
  (:objects b1 b2 b3 - block)
  (:init (emptyhand) (on-table b1) (on b2 b3) (on-table b3) (clear b1) (clear b2)
 (no-detonated b1) (no-destroyed b1) (no-detonated b2) (no-destroyed b2) (no-detonated b3) (no-destroyed b3) (no-destroyed-table))
  (:goal (and (emptyhand) (on b1 b2) (on-table b2) (on-table b3) (clear b1) (clear b3)))
  (:goal-reward 1)
  (:metric maximize (reward))
)
