(define (problem p10)
  (:domain exploding-blocksworld)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 - block)
  (:init (emptyhand) (on-table b1) (on b2 b5) (on b3 b1) (on-table b4) (on b5 b6) (on b6 b8) (on b7 b2) (on-table b8) (clear b3) (clear b4) (clear b7)
 (no-detonated b1) (no-destroyed b1) (no-detonated b2) (no-destroyed b2) (no-detonated b3) (no-destroyed b3) (no-detonated b4) (no-destroyed b4) (no-detonated b5) (no-destroyed b5) (no-detonated b6) (no-destroyed b6)(no-detonated b7) (no-destroyed b7) (no-detonated b8) (no-destroyed b8) (no-destroyed-table)
)
  (:goal (and (emptyhand) (on-table b1) (on-table b2) (on b3 b6) (on-table b4) (on b5 b1) (on b7 b2) (on b6 b7) (on b8 b5) (clear b3) (clear b4) (clear b8)))
  (:goal-reward 1)
  (:metric maximize (reward))
)
